substitutions:
    zone_11: "Bonus Room"
    zone_12: "Upstairs Office"
    zone_13: "Kitchen"
    zone_14: "Master"
    zone_15: "Patio"
    zone_16: "Living Room"

esphome:
  name: monoprice-6ch
  platform: ESP32
  board: nodemcu-32s
  libraries:
    - AsyncTCP

# Enable logging
logger:
  logs:
    monoprice-10761: DEBUG

# Enable Home Assistant API
api:
  password: ""

web_server:

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Monoprice 6Ch Fallback Hotspot"
    password: !secret ap_password

captive_portal:

uart:
  id: uart_bus
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600

external_components:
  - source:
      type: local
      path: components
    components: [ monoprice_10761 ]

monoprice_10761:
  id: monoprice
  uart_id: uart_bus
  update_interval: 1h # Issuing commands makes a bit of background noise, so lets keep it low.
  inputs:
    - number: 1
      name: "Soundconnect"
    - number: 2
      hide: true
    - number: 3
      hide: true
    - number: 4
      hide: true
    - number: 5
      hide: true
    - number: 6
      hide: true

switch:
  - platform: monoprice_10761
    name: "${zone_11} Power"
    zone: 11
    command: "PR"
  - platform: monoprice_10761
    name: "${zone_12} Power"
    zone: 12
    command: "PR"
  - platform: monoprice_10761
    name: "${zone_13} Power"
    zone: 13
    command: "PR"
  - platform: monoprice_10761
    name: "${zone_14} Power"
    zone: 14
    command: "PR"
  - platform: monoprice_10761
    name: "${zone_15} Power"
    zone: 15
    command: "PR"
  - platform: monoprice_10761
    name: "${zone_16} Power"
    zone: 16
    command: "PR"

  - platform: restart
    name: "EspHome Restart"

  - platform: template
    name: "Update all zones"
    id: update_zones
    turn_on_action:
      - component.update: monoprice

select:
  - platform: monoprice_10761
    name: "${zone_13} Input"
    zone: 13
    command: "CH"

number:
  - platform: monoprice_10761
    name: "${zone_13} Volume"
    zone: 13
    command: "VO"

  - platform: monoprice_10761
    name: "${zone_13} Balance"
    zone: 13
    command: "BL"

  - platform: monoprice_10761
    name: "${zone_13} Bass"
    zone: 13
    command: "BS"

  - platform: monoprice_10761
    name: "${zone_13} Trebel"
    zone: 13
    command: "TR"

binary_sensor:
  - platform: monoprice_10761
    name: "${zone_11} Keypad Status"
    zone: 11
    command: LS

text_sensor:
  - platform: template
    name: Uptime Human Readable
    id: uptime_human
    icon: mdi:clock-start
sensor:
  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor
    update_interval: 15s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();
