substitutions:
    zone_11: "Bonus Room"
    zone_12: "Upstairs Office"
    zone_13: "Kitchen"
    zone_14: "Master"
    zone_15: "Patio"
    zone_16: "Living Room"

esphome:
  name: monoprice-6ch-wt32-eth01
  platform: ESP32
  board: esp-wrover-kit
  libraries:
    - AsyncTCP

# Enable logging
logger:
  logs:
    monoprice-10761: DEBUG

# Enable Home Assistant API
api:
  password: ""

web_server:

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

ota:
  password: ""

  # wifi cannot be enabled with ethernet
  # wifi:
  #   ssid: !secret wifi_ssid
  #   password: !secret wifi_password
  # 
  #   # Enable fallback hotspot (captive portal) in case wifi connection fails
  #   ap:
  #     ssid: "Monoprice 6Ch Fallback Hotspot"
  #     password: !secret ap_password
  # 
  # captive_portal:

uart:
  id: uart_bus
  tx_pin: 17 # 17
  rx_pin: 5  # 16
  baud_rate: 9600

external_components:
  - source:
      type: local
      path: components
    components: [ monoprice_10761 ]

monoprice_10761:
  id: monoprice
  uart_id: uart_bus
  update_interval: 1h # Issuing commands makes a bit of background noise, so lets keep it low.
  inputs:
    - number: 1
      name: "Soundconnect"
    - number: 2
      hide: true
    - number: 3
      hide: true
    - number: 4
      hide: true
    - number: 5
      hide: true
    - number: 6
      hide: true

switch:
  - platform: gpio
    name: "PA Mode"
    pin:
      number: 15
      inverted: true
  - platform: monoprice_10761
    name: "${zone_11} Power"
    zone: 11
    command: "PR"
  - platform: monoprice_10761
    name: "${zone_11} Mute"
    zone: 11
    command: "MU"
  - platform: monoprice_10761
    name: "${zone_12} Power"
    zone: 12
    command: "PR"
  - platform: monoprice_10761
    name: "${zone_12} Mute"
    zone: 12
    command: "MU"
  - platform: monoprice_10761
    name: "${zone_13} Power"
    zone: 13
    command: "PR"
  - platform: monoprice_10761
    name: "${zone_13} Mute"
    zone: 13
    command: "MU"
  - platform: monoprice_10761
    name: "${zone_14} Power"
    zone: 14
    command: "PR"
  - platform: monoprice_10761
    name: "${zone_14} Mute"
    zone: 14
    command: "MU"
  - platform: monoprice_10761
    name: "${zone_15} Power"
    zone: 15
    command: "PR"
  - platform: monoprice_10761
    name: "${zone_15} Mute"
    zone: 15
    command: "MU"
  - platform: monoprice_10761
    name: "${zone_16} Power"
    zone: 16
    command: "PR"
  - platform: monoprice_10761
    name: "${zone_16} Mute"
    zone: 16
    command: "MU"

  - platform: restart
    name: "EspHome Restart"

  - platform: template
    name: "Update all zones"
    id: update_zones
    turn_on_action:
      - component.update: monoprice

select:
  - platform: monoprice_10761
    name: "${zone_11} Input"
    zone: 11
    command: "CH"
  - platform: monoprice_10761
    name: "${zone_12} Input"
    zone: 12
    command: "CH"
  - platform: monoprice_10761
    name: "${zone_13} Input"
    zone: 13
    command: "CH"
  - platform: monoprice_10761
    name: "${zone_14} Input"
    zone: 14
    command: "CH"
  - platform: monoprice_10761
    name: "${zone_15} Input"
    zone: 15
    command: "CH"
  - platform: monoprice_10761
    name: "${zone_16} Input"
    zone: 16
    command: "CH"

number:
  - platform: monoprice_10761
    name: "${zone_11} Volume"
    zone: 11
    command: "VO"

  - platform: monoprice_10761
    name: "${zone_11} Balance"
    zone: 11
    command: "BL"

  - platform: monoprice_10761
    name: "${zone_11} Bass"
    zone: 11
    command: "BS"

  - platform: monoprice_10761
    name: "${zone_11} Trebel"
    zone: 11
    command: "TR"

  - platform: monoprice_10761
    name: "${zone_12} Volume"
    zone: 12
    command: "VO"

  - platform: monoprice_10761
    name: "${zone_12} Balance"
    zone: 12
    command: "BL"

  - platform: monoprice_10761
    name: "${zone_12} Bass"
    zone: 12
    command: "BS"

  - platform: monoprice_10761
    name: "${zone_12} Trebel"
    zone: 12
    command: "TR"

  - platform: monoprice_10761
    name: "${zone_13} Volume"
    zone: 13
    command: "VO"

  - platform: monoprice_10761
    name: "${zone_13} Balance"
    zone: 13
    command: "BL"

  - platform: monoprice_10761
    name: "${zone_13} Bass"
    zone: 13
    command: "BS"

  - platform: monoprice_10761
    name: "${zone_13} Trebel"
    zone: 13
    command: "TR"

  - platform: monoprice_10761
    name: "${zone_14} Volume"
    zone: 14
    command: "VO"

  - platform: monoprice_10761
    name: "${zone_14} Balance"
    zone: 14
    command: "BL"

  - platform: monoprice_10761
    name: "${zone_14} Bass"
    zone: 14
    command: "BS"

  - platform: monoprice_10761
    name: "${zone_14} Trebel"
    zone: 14
    command: "TR"

  - platform: monoprice_10761
    name: "${zone_15} Volume"
    zone: 15
    command: "VO"

  - platform: monoprice_10761
    name: "${zone_15} Balance"
    zone: 15
    command: "BL"

  - platform: monoprice_10761
    name: "${zone_15} Bass"
    zone: 15
    command: "BS"

  - platform: monoprice_10761
    name: "${zone_15} Trebel"
    zone: 15
    command: "TR"

  - platform: monoprice_10761
    name: "${zone_16} Volume"
    zone: 16
    command: "VO"

  - platform: monoprice_10761
    name: "${zone_16} Balance"
    zone: 16
    command: "BL"

  - platform: monoprice_10761
    name: "${zone_16} Bass"
    zone: 16
    command: "BS"

  - platform: monoprice_10761
    name: "${zone_16} Trebel"
    zone: 16
    command: "TR"

binary_sensor:
  - platform: monoprice_10761
    name: "${zone_11} Keypad Status"
    zone: 11
    command: LS

sensor:
  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor
    update_interval: 15s
